// Static content for scripts/seed-dots.ts — people, role personas, post/reply/DM
// pools. Kept separate so the seeder itself stays readable. Every company
// below is fictional on purpose: seeded profiles must never claim real
// employment at a real organisation.

export type Gender = "m" | "f";
export type RoleKey =
  | "swe" | "design" | "pm" | "data" | "founder" | "photo" | "writer" | "food" | "fitness"
  | "music" | "doctor" | "teacher" | "finance" | "film" | "student" | "art" | "marketing" | "sports";

// [display first name, last name, gender, city, role]
export type Person = readonly [string, string, Gender, string, RoleKey];

export const PEOPLE: Person[] = [
  // ---- men ----
  ["Aarav", "Mehta", "m", "Bengaluru", "swe"],
  ["Vihaan", "Nair", "m", "Kochi", "design"],
  ["Arjun", "Reddy", "m", "Hyderabad", "pm"],
  ["Kabir", "Malhotra", "m", "Delhi", "founder"],
  ["Rohan", "Deshmukh", "m", "Pune", "data"],
  ["Ishaan", "Kapoor", "m", "Mumbai", "photo"],
  ["Aditya", "Iyer", "m", "Chennai", "swe"],
  ["Karthik", "Subramanian", "m", "Chennai", "swe"],
  ["Siddharth", "Rao", "m", "Bengaluru", "data"],
  ["Vivek", "Chauhan", "m", "Jaipur", "finance"],
  ["Rahul", "Bose", "m", "Kolkata", "writer"],
  ["Anirban", "Dutta", "m", "Kolkata", "music"],
  ["Imran", "Qureshi", "m", "Mumbai", "film"],
  ["Farhan", "Ansari", "m", "Lucknow", "marketing"],
  ["Yusuf", "Sheikh", "m", "Hyderabad", "food"],
  ["Gurpreet", "Sandhu", "m", "Chandigarh", "fitness"],
  ["Harjot", "Gill", "m", "Ludhiana", "sports"],
  ["Manav", "Trivedi", "m", "Ahmedabad", "founder"],
  ["Parth", "Shah", "m", "Surat", "finance"],
  ["Dhruv", "Patel", "m", "Ahmedabad", "swe"],
  ["Omkar", "Kulkarni", "m", "Pune", "music"],
  ["Sameer", "Joshi", "m", "Nashik", "teacher"],
  ["Tejas", "Gaikwad", "m", "Mumbai", "sports"],
  ["Nikhil", "Verma", "m", "Noida", "swe"],
  ["Ayaan", "Khan", "m", "Delhi", "design"],
  ["Reyansh", "Gupta", "m", "Delhi", "student"],
  ["Krish", "Pillai", "m", "Thiruvananthapuram", "student"],
  ["Varun", "Menon", "m", "Kochi", "doctor"],
  ["Naveen", "Naidu", "m", "Visakhapatnam", "pm"],
  ["Srikanth", "Varma", "m", "Hyderabad", "swe"],
  ["Ramesh", "Iyengar", "m", "Mysuru", "teacher"],
  ["Ganesh", "Hegde", "m", "Mangaluru", "founder"],
  ["Prateek", "Mishra", "m", "Varanasi", "student"],
  ["Ankit", "Tiwari", "m", "Bhopal", "marketing"],
  ["Abhishek", "Pandey", "m", "Gurugram", "swe"],
  ["Deepak", "Yadav", "m", "Patna", "sports"],
  ["Sourav", "Sen", "m", "Kolkata", "photo"],
  ["Debashish", "Mukherjee", "m", "Kolkata", "doctor"],
  ["Ritwik", "Banerjee", "m", "Kolkata", "film"],
  ["Tanmay", "Bhatt", "m", "Vadodara", "writer"],
  ["Yash", "Agarwal", "m", "Indore", "finance"],
  ["Mohit", "Saxena", "m", "Bengaluru", "data"],
  ["Kunal", "Arora", "m", "Delhi", "marketing"],
  ["Sahil", "Bhatia", "m", "Delhi", "fitness"],
  ["Rishi", "Menon", "m", "Bengaluru", "art"],
  ["Jay", "Desai", "m", "Mumbai", "student"],
  ["Abel", "Thomas", "m", "Kottayam", "music"],
  ["Joseph", "Fernandes", "m", "Goa", "photo"],
  ["Neil", "D'Souza", "m", "Goa", "food"],
  // ---- women ----
  ["Ananya", "Sharma", "f", "Delhi", "design"],
  ["Diya", "Kapoor", "f", "Mumbai", "art"],
  ["Isha", "Malhotra", "f", "Gurugram", "pm"],
  ["Kavya", "Nair", "f", "Bengaluru", "swe"],
  ["Priya", "Menon", "f", "Kochi", "doctor"],
  ["Riya", "Shah", "f", "Mumbai", "finance"],
  ["Saanvi", "Reddy", "f", "Hyderabad", "data"],
  ["Neha", "Gupta", "f", "Noida", "marketing"],
  ["Pooja", "Kulkarni", "f", "Pune", "teacher"],
  ["Anjali", "Mishra", "f", "Lucknow", "writer"],
  ["Meera", "Iyer", "f", "Chennai", "music"],
  ["Divya", "Krishnan", "f", "Chennai", "swe"],
  ["Lakshmi", "Naidu", "f", "Vijayawada", "doctor"],
  ["Deepika", "Rao", "f", "Bengaluru", "design"],
  ["Swati", "Joshi", "f", "Pune", "founder"],
  ["Anitha", "Pillai", "f", "Thiruvananthapuram", "teacher"],
  ["Simran", "Kaur", "f", "Amritsar", "fitness"],
  ["Harleen", "Kaur", "f", "Chandigarh", "food"],
  ["Manpreet", "Bedi", "f", "Ludhiana", "student"],
  ["Ayesha", "Siddiqui", "f", "Hyderabad", "writer"],
  ["Zainab", "Khan", "f", "Mumbai", "film"],
  ["Sana", "Sheikh", "f", "Mumbai", "marketing"],
  ["Salma", "Farooqui", "f", "Lucknow", "doctor"],
  ["Mariam", "Baig", "f", "Bhopal", "student"],
  ["Maria", "Fernandes", "f", "Goa", "food"],
  ["Anita", "Pereira", "f", "Mumbai", "teacher"],
  ["Susan", "George", "f", "Kochi", "finance"],
  ["Liza", "Varghese", "f", "Kottayam", "doctor"],
  ["Ipsita", "Chatterjee", "f", "Kolkata", "art"],
  ["Moumita", "Dutta", "f", "Kolkata", "music"],
  ["Sreya", "Sen", "f", "Kolkata", "writer"],
  ["Shreya", "Deshmukh", "f", "Pune", "pm"],
  ["Sanika", "Kelkar", "f", "Pune", "photo"],
  ["Rutuja", "Patil", "f", "Pune", "swe"],
  ["Nikita", "Trivedi", "f", "Ahmedabad", "founder"],
  ["Khushi", "Patel", "f", "Ahmedabad", "marketing"],
  ["Aditi", "Chauhan", "f", "Jaipur", "data"],
  ["Tanvi", "Rathore", "f", "Jodhpur", "film"],
  ["Kritika", "Yadav", "f", "Hisar", "sports"],
  ["Ishita", "Bansal", "f", "Delhi", "finance"],
  ["Rhea", "Fernandes", "f", "Bengaluru", "fitness"],
  ["Ritika", "Sethi", "f", "Delhi", "photo"],
  ["Aarohi", "Deshpande", "f", "Nagpur", "art"],
  ["Myra", "Chandran", "f", "Kochi", "swe"],
  ["Tara", "Krishnan", "f", "Chennai", "film"],
  ["Zoya", "Ahmed", "f", "Bengaluru", "design"],
  ["Aisha", "Qureshi", "f", "Hyderabad", "data"],
  ["Pranati", "Mohanty", "f", "Bhubaneswar", "student"],
  ["Bhakti", "Jadhav", "f", "Kolhapur", "sports"],
  ["Devika", "Nambiar", "f", "Kozhikode", "food"],
];

export type RolePersona = {
  titles: string[];
  companies: string[];
  taglines: string[];
  skills: string[];
  institutions: string[];
  degree: string;
  field: string;
  themes: string[]; // free theme preset keys only
  posts: string[];
};

export const ROLES: Record<RoleKey, RolePersona> = {
  swe: {
    titles: ["Software Engineer", "Backend Engineer", "Full-stack Developer", "Staff Engineer"],
    companies: ["Nilgiri Labs", "Kaveri Systems", "Tarang Cloud", "Sundial Software"],
    taglines: ["Shipping code, breaking nothing (mostly).", "Backend at heart, curious about everything.", "Turning coffee into pull requests.", "Small PRs, big impact."],
    skills: ["TypeScript", "Go", "PostgreSQL", "System Design", "React", "Kubernetes"],
    institutions: ["NIT Trichy", "BITS Pilani", "IIIT Hyderabad", "VIT Vellore"],
    degree: "B.Tech", field: "Computer Science",
    themes: ["ocean", "midnight", "default"],
    posts: [
      "Spent 3 hours chasing a bug. It was a missing await. Every. Single. Time.",
      "Hot take: the best code review comment is a question, not a command.",
      "Deleted 2,000 lines today and the app got faster. Best commit of the week.",
      "Finally moved our cron jobs to a proper queue. Sleeping better already.",
      "If your README doesn't say how to run the project in under 5 minutes, it's not done.",
      "Learning Rust on weekends. The compiler is the strictest mentor I've ever had, and I kind of love it.",
      "Standup tip: say what's blocking you first. Everything else is noise.",
      "Nothing humbles you like reading your own code from six months ago.",
    ],
  },
  design: {
    titles: ["Product Designer", "UX Designer", "Design Lead", "Visual Designer"],
    companies: ["Tarang Studio", "Chitra Design Co.", "Pixel Haveli", "Rangoli Labs"],
    taglines: ["Making software feel human.", "Pixels, patterns and a lot of chai.", "Design is how it works, not how it looks.", "Sketching first, Figma later."],
    skills: ["Figma", "UX Research", "Design Systems", "Prototyping", "Typography", "Accessibility"],
    institutions: ["NID Ahmedabad", "IDC IIT Bombay", "Srishti Manipal", "MIT Institute of Design"],
    degree: "M.Des", field: "Interaction Design",
    themes: ["rose", "sunset", "default"],
    posts: [
      "Spent the whole morning on 2px of padding. Worth it.",
      "Devanagari and Tamil type deserve better UI defaults. Designing for India means designing for every script.",
      "User interviews beat opinions. Five conversations changed our whole roadmap this week.",
      "Reminder: your users are on a 5-year-old Android phone with patchy 4G. Design for that first.",
      "A good empty state is a tiny piece of hospitality.",
      "Sketched the whole flow on paper first. Figma took 20 minutes instead of 2 days.",
      "Dark mode isn't just inverted colours. It's a whole second design. Learned that the hard way.",
      "Big fan of interfaces that say less and do more.",
    ],
  },
  pm: {
    titles: ["Product Manager", "Senior PM", "Group Product Manager", "Associate PM"],
    companies: ["Kaveri Systems", "Bharat Pay Labs", "Sundial Software", "Nilgiri Labs"],
    taglines: ["Obsessed with the problem, flexible on the solution.", "Roadmaps in pencil, principles in ink.", "Talking to users so you don't have to guess.", "Shipping the smallest thing that teaches us something."],
    skills: ["Product Strategy", "Roadmapping", "SQL", "A/B Testing", "User Research", "Stakeholder Management"],
    institutions: ["IIM Bangalore", "ISB Hyderabad", "IIT Delhi", "XLRI Jamshedpur"],
    degree: "MBA", field: "Product & Strategy",
    themes: ["midnight", "ocean", "default"],
    posts: [
      "The hardest part of product isn't building. It's deciding what NOT to build.",
      "A feature request is a symptom. Ask 'why' five times before you write the spec.",
      "Killed a feature we loved because the data said no. Painful, correct.",
      "Best PM habit I've picked up: write the press release before writing the PRD.",
      "Metrics without a hypothesis are just decoration.",
      "Spent the day in customer calls instead of meetings. Never going back.",
      "Roadmap season again. May the best assumptions win.",
      "If everything is priority one, nothing is.",
    ],
  },
  data: {
    titles: ["Data Scientist", "ML Engineer", "Data Analyst", "Analytics Lead"],
    companies: ["Masala Analytics", "Kaveri Systems", "Tarang Cloud", "Neel AI"],
    taglines: ["Finding the story in the spreadsheet.", "Models are cheap, good questions aren't.", "Turning messy data into decisions.", "Python by day, cricket stats by night."],
    skills: ["Python", "Machine Learning", "SQL", "Statistics", "PyTorch", "Data Visualisation"],
    institutions: ["IISc Bangalore", "ISI Kolkata", "IIT Madras", "IIIT Bangalore"],
    degree: "M.Tech", field: "Data Science",
    themes: ["forest", "ocean", "midnight"],
    posts: [
      "80% of data science is cleaning data. The other 20% is explaining why it needed cleaning.",
      "Correlation looked beautiful. Turned out to be one duplicated column. Humbling.",
      "A simple baseline beats a fancy model you can't explain. Every time.",
      "Plotting IPL powerplay numbers again. The trends are wild.",
      "Reminder: accuracy is a terrible metric on imbalanced data.",
      "Your dashboard doesn't need 14 charts. It needs one clear answer.",
      "Reading papers on weekends is my version of a hobby now.",
      "Feature engineering is still where the magic is.",
    ],
  },
  founder: {
    titles: ["Founder & CEO", "Co-founder", "Founder", "Founder & CTO"],
    companies: ["Kisan Connect", "Dabba Labs", "Swadesh Works", "Chai & Code Ventures"],
    taglines: ["Building in public, learning out loud.", "Solving a boring problem for a billion people.", "Bootstrapped, caffeinated, hopeful.", "Trying to make small businesses' lives easier."],
    skills: ["Fundraising", "Go-to-Market", "Hiring", "Product Vision", "Sales", "Operations"],
    institutions: ["IIT Kharagpur", "NIT Surathkal", "SRCC Delhi", "BITS Pilani"],
    degree: "B.Tech", field: "Industrial Engineering",
    themes: ["sunset", "forest", "default"],
    posts: [
      "Month 8 of building. Revenue is small, learning is enormous. Not complaining.",
      "First paying customer today. Framed the invoice. Not kidding.",
      "Nobody tells you that founder life is 10% strategy and 90% following up.",
      "Hiring lesson: attitude and curiosity beat a perfect résumé.",
      "Talked to 30 kirana store owners this month. Every assumption we had was slightly wrong.",
      "Bootstrapping means every rupee has to justify itself. Oddly freeing.",
      "Rejected by 12 investors, loved by 12 customers. I know which group to listen to.",
      "Shipping on Friday evening because we have no fear and no ops team.",
    ],
  },
  photo: {
    titles: ["Photographer", "Street Photographer", "Travel & Portrait Photographer", "Visual Storyteller"],
    companies: ["Lens & Light Studio", "Golden Hour Collective", "Freelance", "Ghat Road Pictures"],
    taglines: ["Chasing golden hour, one frame at a time.", "Light, shadow and the occasional stray dog.", "Photographing ordinary moments.", "Film when I can, digital when I must."],
    skills: ["Portrait Photography", "Lightroom", "Street Photography", "Storytelling", "Color Grading", "Film Photography"],
    institutions: ["Sophia Polytechnic", "Delhi College of Art", "Symbiosis Pune", "St. Xavier's College"],
    degree: "B.A.", field: "Visual Communication",
    themes: ["sunset", "rose", "default"],
    posts: [
      "Woke up at 5am for sunrise. Clouds ruined it. The chai vendor's smile did not.",
      "Best photo of the month was taken on my phone, of a stranger laughing at a bus stop.",
      "Monsoon light is unreal. Every puddle is a mirror.",
      "Shot my first roll of film in a year. Half were blurry, all were precious.",
      "Rule of thirds is a suggestion. Feelings are the rule.",
      "Old Delhi lanes at dawn. Worth every wrong turn.",
      "Gear doesn't matter until light does.",
      "Editing tip: less contrast, more patience.",
    ],
  },
  writer: {
    titles: ["Writer", "Journalist", "Editor", "Columnist"],
    companies: ["The Daily Meridian", "Kathakaar Press", "Freelance", "Aksharam Media"],
    taglines: ["Words, walks and unfinished drafts.", "Writing my way through the city.", "Reader first, writer second.", "Long-form lover in a short-form world."],
    skills: ["Long-form Writing", "Editing", "Research", "Storytelling", "Copywriting", "Translation"],
    institutions: ["Delhi University", "Presidency College", "St. Xavier's College", "Jadavpur University"],
    degree: "M.A.", field: "English Literature",
    themes: ["rose", "midnight", "default"],
    posts: [
      "First draft is telling yourself the story. Second draft is telling it to everyone else.",
      "Re-reading old Premchand stories this month. Still devastating, still relevant.",
      "The best writing advice I've ever received: cut the first paragraph.",
      "Spent a full day on one sentence. It's still not right. It's still my favourite.",
      "Writing in Hindi and English feels like using two different hands for the same heart.",
      "Rainy day + a stack of unread books = the good life.",
      "Working on a long piece about small-town libraries. So many stories in one room.",
      "You don't find time to write. You steal it.",
    ],
  },
  food: {
    titles: ["Chef", "Food Blogger", "Home Baker", "Culinary Creator"],
    companies: ["Tadka House", "The Spice Route", "Freelance", "Kitchen Diaries"],
    taglines: ["Feeding people is my love language.", "Recipes, stories and a lot of ghee.", "Trying every street food so you don't have to.", "Home-style flavours, restaurant-style love."],
    skills: ["Regional Indian Cuisine", "Baking", "Food Photography", "Menu Design", "Recipe Development", "Fermentation"],
    institutions: ["IHM Mumbai", "Welcomgroup Graduate School", "IHM Pusa Delhi", "Culinary Academy of India"],
    degree: "B.Sc.", field: "Hospitality & Hotel Administration",
    themes: ["sunset", "rose", "default"],
    posts: [
      "Made my nani's dal today. Mine is not as good. Nobody's is.",
      "There's no such thing as too much ghee. Fight me.",
      "Street food ranking, Hyderabad edition: Irani chai and osmania biscuit, always number one.",
      "Tried fermenting idli batter in winter. Patience and a warm oven fixed everything.",
      "Cooked for 20 people this weekend. Tired, happy, out of jeera.",
      "The secret of a good biryani is patience. And good rice. Mostly patience.",
      "Monsoon evenings need pakoras. This is not a debate.",
      "Every family recipe is a story with measurements missing.",
    ],
  },
  fitness: {
    titles: ["Fitness Coach", "Yoga Instructor", "Strength Coach", "Wellness Trainer"],
    companies: ["Prana Fitness", "Iron Temple Gym", "Freelance", "Surya Wellness"],
    taglines: ["Move daily, eat well, sleep more.", "Strong body, calm mind.", "Consistency over intensity.", "Yoga at dawn, deadlifts by dusk."],
    skills: ["Strength Training", "Yoga", "Nutrition Coaching", "Mobility", "Running", "Habit Building"],
    institutions: ["Lakshmibai National Institute of Physical Education", "Kaivalyadhama", "Punjab University", "Symbiosis Pune"],
    degree: "B.P.Ed.", field: "Physical Education",
    themes: ["forest", "sunset", "default"],
    posts: [
      "5:30am run done. The city is so quiet at that hour, you almost forget how loud it gets.",
      "Skipped the gym once, then twice. The habit is fragile. Back at it today.",
      "Protein intake in Indian diets is underrated. Dal, paneer, curd, eggs. Start there.",
      "Your best workout is the one you actually do.",
      "Sleep is a training variable. Treat it like one.",
      "Ten minutes of surya namaskar changed my mornings more than any supplement.",
      "Progress photos are cute. Progress feelings are better.",
      "Nobody's motivated every day. Build the system, not the mood.",
    ],
  },
  music: {
    titles: ["Musician", "Music Producer", "Singer-Songwriter", "Music Teacher"],
    companies: ["Sur Sangam Studio", "Raaga Records", "Freelance", "Tanpura Collective"],
    taglines: ["Sa Re Ga Ma, and everything in between.", "Melodies, monsoons and midnight practice.", "Fusion of everything I love.", "Writing songs in three languages."],
    skills: ["Hindustani Vocals", "Guitar", "Music Production", "Songwriting", "Tabla", "Live Performance"],
    institutions: ["Rabindra Bharati University", "KM Music Conservatory", "Gandharva Mahavidyalaya", "Berklee Online"],
    degree: "B.Mus.", field: "Music Performance",
    themes: ["midnight", "rose", "default"],
    posts: [
      "Riyaz at 6am. The tanpura hum is my alarm clock and therapist.",
      "Wrote a melody in the shower and forgot it before I got out. Every time.",
      "Raag Yaman on a rainy evening. Nothing else needs to happen today.",
      "Recorded a demo in my bedroom with a single mic. Imperfect, honest, mine.",
      "Playing for 40 people felt bigger than any stadium show.",
      "Fusion works when both sides listen, not when both sides talk.",
      "Old Kishore Kumar records still teach me something every time.",
      "Practice slowly. Everything else follows.",
    ],
  },
  doctor: {
    titles: ["Physician", "Paediatrician", "Resident Doctor", "General Practitioner"],
    companies: ["Sanjeevani Hospital", "Arogya Clinic", "City Care Medical", "Dhanvantari Health"],
    taglines: ["Listening is half the diagnosis.", "Medicine, mindfulness and lots of chai.", "Here to heal and to learn.", "Public health enthusiast."],
    skills: ["Internal Medicine", "Patient Communication", "Public Health", "Emergency Care", "Preventive Medicine", "Medical Research"],
    institutions: ["AIIMS Delhi", "CMC Vellore", "Grant Medical College", "Government Medical College"],
    degree: "MBBS", field: "Medicine",
    themes: ["ocean", "forest", "default"],
    posts: [
      "Drink water. Sleep properly. Walk daily. Boring advice that works.",
      "Night shift chai hits different. Don't ask how many cups.",
      "The kindest patients are often the sickest. Always humbling.",
      "Antibiotics don't work on viral fevers. Please stop asking us for them.",
      "A doctor's real superpower is explaining things simply.",
      "Small-town clinics do heroic work without any applause.",
      "Long shift over. Grateful for my team, my tea, and my bed.",
      "Vaccinate your kids. That's the whole post.",
    ],
  },
  teacher: {
    titles: ["Teacher", "Mathematics Educator", "Professor", "School Principal"],
    companies: ["Vidya Mandir School", "Gyan Bharati Academy", "Sarvodaya Institute", "Freelance Tutor"],
    taglines: ["Teaching is learning twice.", "Making maths less scary.", "Curiosity is the curriculum.", "Every classroom has a future scientist."],
    skills: ["Curriculum Design", "Mathematics", "Classroom Management", "Storytelling", "EdTech", "Mentoring"],
    institutions: ["Delhi University", "Pune University", "Mysore University", "Tata Institute of Social Sciences"],
    degree: "B.Ed.", field: "Education",
    themes: ["forest", "ocean", "default"],
    posts: [
      "A student who asked 'why' today taught me more than my whole syllabus.",
      "Explaining fractions with rotis works better than any diagram.",
      "Exam results are a moment. Curiosity is a lifetime.",
      "Marks measure memory. Questions measure understanding.",
      "Best classroom moment: a shy kid finally raising their hand.",
      "Teaching in two languages has made me a better explainer in both.",
      "Parent-teacher meeting day. Tea helps. Patience helps more.",
      "If a child isn't learning the way you teach, teach the way they learn.",
    ],
  },
  finance: {
    titles: ["Chartered Accountant", "Financial Analyst", "Investment Advisor", "Tax Consultant"],
    companies: ["Lakshmi Advisory", "Mint Street Partners", "Bharat Capital", "Arthashastra Consulting"],
    taglines: ["Making money boring, in a good way.", "Numbers with a human face.", "Compound interest is my favourite person.", "Budgets, taxes and unnecessary spreadsheets."],
    skills: ["Financial Modelling", "Tax Planning", "Auditing", "Mutual Funds", "Excel", "Risk Analysis"],
    institutions: ["SRCC Delhi", "ICAI", "NMIMS Mumbai", "Christ University"],
    degree: "B.Com", field: "Accounting & Finance",
    themes: ["midnight", "ocean", "default"],
    posts: [
      "Start a SIP. Even a small one. Time in the market beats timing the market.",
      "Every March, everyone remembers tax saving. Start in April instead.",
      "An emergency fund is boring until the day it's the only thing you have.",
      "Explaining GST to a chai-stall owner taught me more than any textbook.",
      "Budgeting isn't restriction, it's permission to spend without guilt.",
      "The best investment is the one you understand.",
      "Spreadsheet formulas are a love language.",
      "Inflation is the quiet tax. Plan around it.",
    ],
  },
  film: {
    titles: ["Filmmaker", "Cinematographer", "Video Editor", "Documentary Maker"],
    companies: ["Chalchitra Films", "Nukkad Pictures", "Freelance", "Kadha Studios"],
    taglines: ["Telling stories in 24 frames a second.", "Documentaries, short films and endless retakes.", "Cinema is a conversation.", "Cutting rooms are my happy place."],
    skills: ["Cinematography", "Video Editing", "Screenwriting", "Colour Grading", "Direction", "Sound Design"],
    institutions: ["FTII Pune", "Satyajit Ray Film Institute", "Whistling Woods", "AJK MCRC Jamia"],
    degree: "Diploma", field: "Film & Television",
    themes: ["midnight", "sunset", "default"],
    posts: [
      "Wrapped a short film shoot. 14 hours, 3 locations, one very patient chai vendor.",
      "The edit is where the film is actually made.",
      "Watched a Satyajit Ray classic again. Stillness can say more than any dialogue.",
      "Natural light or nothing. Been saying it for years.",
      "Low budget doesn't mean low imagination.",
      "Our documentary premiered to a room of 30 people. Best 30 people ever.",
      "Sound is half the picture and no one notices until it's wrong.",
      "Every story finds its ending in the edit, not the script.",
    ],
  },
  student: {
    titles: ["Student", "Engineering Student", "Final-year Student", "Research Intern"],
    companies: ["College Placement Cell", "Campus Tech Club", "Student Ventures", "University Research Lab"],
    taglines: ["Learning in public.", "Semester exams and sleep-deprivation.", "Curious, caffeinated, in progress.", "Figuring it out, one assignment at a time."],
    skills: ["Python", "Public Speaking", "Web Development", "Research", "Writing", "Teamwork"],
    institutions: ["Delhi University", "Anna University", "Savitribai Phule Pune University", "Jadavpur University"],
    degree: "B.Tech", field: "Computer Science",
    themes: ["ocean", "sunset", "default"],
    posts: [
      "Mid-sems done. Sleep debt: enormous.",
      "Campus canteen chai is the only reason I attend 8am lectures.",
      "Applied to 20 internships. Heard back from 2. Still counting it as a win.",
      "Group projects: 1 person does the work, 3 people do the slides.",
      "Just built my first web app. It's ugly. It works. I'm so proud.",
      "Hostel life: 2am maggi is a personality trait.",
      "Started a small coding club on campus. 12 members already.",
      "Reminder to self: comparison is the thief of joy, and LinkedIn is its accomplice.",
    ],
  },
  art: {
    titles: ["Illustrator", "Visual Artist", "Painter", "Digital Artist"],
    companies: ["Rang Studio", "Freelance", "Kalakriti Gallery", "Madhubani Collective"],
    taglines: ["Colours, chaos and coffee stains.", "Drawing the world I want to live in.", "Ink on paper, heart on sleeve.", "Traditional roots, modern lines."],
    skills: ["Illustration", "Watercolour", "Procreate", "Character Design", "Madhubani Art", "Printmaking"],
    institutions: ["JJ School of Art", "Kala Bhavana Santiniketan", "College of Art Delhi", "Chitrakala Parishath"],
    degree: "BFA", field: "Painting",
    themes: ["rose", "sunset", "default"],
    posts: [
      "Finished a Madhubani piece after three weeks. My hands and my heart are tired and full.",
      "Sketched the neighbourhood chai stall today. Every face is a story.",
      "Art block is real. Walking is the only cure I've found.",
      "Watercolour teaches you to let go. Oil teaches you to commit.",
      "Sold my first print today. Cried a little. Ordered more paper.",
      "The city is a sketchbook if you look at it right.",
      "Colours of a Rajasthan sunset are impossible to mix. I keep trying.",
      "Draw badly every day. That's the whole secret.",
    ],
  },
  marketing: {
    titles: ["Marketing Manager", "Brand Strategist", "Content Marketer", "Growth Marketer"],
    companies: ["Brand Bazaar", "Tarang Studio", "Growth Chai", "Kaveri Systems"],
    taglines: ["Stories that sell, without selling out.", "Growth, with a heart.", "Brands are people. Treat them that way.", "Words, data and stubborn optimism."],
    skills: ["Brand Strategy", "SEO", "Content Marketing", "Analytics", "Copywriting", "Social Media"],
    institutions: ["MICA Ahmedabad", "Symbiosis Pune", "Christ University", "IIM Indore"],
    degree: "PGDM", field: "Marketing",
    themes: ["sunset", "rose", "default"],
    posts: [
      "The best marketing is a product people can't stop talking about.",
      "Vernacular content is the next big wave in India. Not a trend, a reality.",
      "Your audience doesn't want to be advertised to. They want to be understood.",
      "A/B tested the headline. The boring one won. Sigh.",
      "Festival season campaigns: plan in August, panic in October.",
      "Brand voice is how you talk when nobody's writing the script.",
      "Repeat after me: reach is not revenue.",
      "Wrote 40 headlines today. Kept one. That's the job.",
    ],
  },
  sports: {
    titles: ["Cricket Coach", "Athlete", "Sports Journalist", "Kabaddi Player"],
    companies: ["District Sports Academy", "State Cricket Association", "Freelance", "Khel Bharati Academy"],
    taglines: ["Play hard, play fair, play again.", "Cricket is life, the rest is details.", "Early mornings on the ground.", "Sport builds character."],
    skills: ["Coaching", "Cricket", "Fitness Training", "Team Leadership", "Sports Analytics", "Kabaddi"],
    institutions: ["Punjab University", "Mumbai University", "NIS Patiala", "Delhi University"],
    degree: "B.P.Ed.", field: "Sports Science",
    themes: ["forest", "ocean", "default"],
    posts: [
      "Under-16 trials this morning. So much raw talent in small towns.",
      "Nothing beats gully cricket with a taped tennis ball.",
      "IPL auction was chaos. As always. I stayed up too late again.",
      "Coaching kids taught me patience faster than any job.",
      "Fielding wins matches. Nobody puts fielding on posters.",
      "Kabaddi is the smartest chess game played at full speed.",
      "Ran 8km before sunrise. The ground was empty and perfect.",
      "Sport isn't just about winning. It's about who you become while losing.",
    ],
  },
};

// City-agnostic posts anyone could write. {city} is substituted per author.
export const GENERIC_POSTS: string[] = [
  "Good morning {city}. Chai first, everything else later.",
  "Traffic in {city} today was a special kind of chaos. Took 40 minutes for 5 km.",
  "Monsoon is finally here in {city} and my mood has improved by 200%.",
  "Missing home-cooked food more than I'll admit. Ammi's, Amma's, Maa's, doesn't matter, it's all love.",
  "Weekend plan: sleep, chai, a good book, repeat.",
  "Diwali is close and I'm already dreaming of mithai.",
  "Sunday is for long walks and doing absolutely nothing.",
  "Just discovered a tiny café in {city} with the best filter coffee. Not telling where yet.",
  "Power cut, candlelight, old songs. Unexpectedly perfect evening.",
  "Small joys: the first sip of chai, a green signal, an empty seat in the metro.",
  "Long train journeys are underrated. Window seat, playlist, chai at every station.",
  "Started reading again after a long break. Forgot how good it feels.",
  "Nothing beats a rainy afternoon and hot pakoras. {city} nailed it today.",
  "The auto driver and I discussed politics, cricket and life in a 10-minute ride. Only in India.",
  "Cutting down on screen time this month. Ask me how it's going in a week.",
  "Grateful for friends who show up without being asked.",
  "Cricket on the TV, chai in hand, family around. Sunday perfection.",
  "Learning a new language this year. Progress is slow. Pride is high.",
  "Every city has a smell that means home. {city}'s hits me every time I come back.",
  "Autumn evenings in {city} are so underrated.",
  "Booked a trip to the hills. Someone stop me from checking my emails there.",
  "Slow mornings, warm sunlight, no notifications. Should do this more.",
  "Unpopular opinion: filter coffee > any fancy latte.",
  "Wedding season is here. My calendar and my waistline are both in danger.",
  "Reached out to an old friend after two years. It was like no time had passed.",
  "Silence is loud in a city like {city}. I found a pocket of it today.",
  "Happy to be here. Hi everyone, looking forward to meeting good people on 0dot.",
  "Small wins count. Today I finally finished the thing I'd been putting off for a month.",
  "The best conversations happen after midnight.",
  "Started journaling. Three lines a day. Already feels different.",
];

// Short replies that read naturally under almost any post.
export const REPLIES: string[] = [
  "This is so true 🙌",
  "Well said.",
  "Needed to read this today, thank you.",
  "Haha, relatable!",
  "Congratulations! Well deserved 🎉",
  "Bookmarked. Thanks for sharing this.",
  "100% agree.",
  "Love this perspective.",
  "Wow, that's beautiful.",
  "This made my day 😊",
  "Would love to hear more about this!",
  "Same here. Every single time.",
  "Big respect 👏",
  "Couldn't have said it better.",
  "Sending you good vibes!",
  "You always post the best stuff.",
  "This deserves way more attention.",
  "Ha! I felt this in my soul.",
  "Thank you for saying it out loud.",
  "Absolutely. Sharing this with my team.",
  "Let's catch up soon, we should discuss this over chai ☕",
  "So proud of you!",
  "Yes! Finally someone said it.",
  "That's a whole mood.",
  "Quietly one of the best posts I've read this week.",
  "Interesting. I'd never thought about it this way.",
  "Please write more about this!",
  "Kudos! Keep going 💪",
  "Wonderful. Loved every word.",
  "This is gold, thank you!",
];

// Each script is alternating lines: even index = person A, odd = person B.
// {a} and {b} are first names of the two people.
export const DM_SCRIPTS: string[][] = [
  ["Hey {b}, loved your recent post!", "Thanks {a}! Really appreciate that 😊", "Are you free for a quick call this week?", "Sure, Thursday evening works?", "Perfect. I'll send a link."],
  ["Hi {b}! We should collaborate on something.", "Hey {a}, I'd love that. What did you have in mind?", "Something small to start. Can share details tomorrow.", "Sounds good. Looking forward to it!"],
  ["{b}, are you coming to the meetup this weekend?", "Yes! Just confirmed my spot.", "Great, see you there. Chai on me ☕", "Deal 😄"],
  ["Hey {b}, quick question. How did you get started?", "Honestly, curiosity and a lot of mistakes 😅", "Ha, that's the best way. Any advice for a beginner?", "Start small, ship often, and don't compare yourself to others.", "Thank you, that really helps."],
  ["Happy Diwali {b}! 🪔", "Happy Diwali {a}! Wishing you and family lots of joy ✨", "Thanks! Save some mithai for me."],
  ["{b} your profile is really well done!", "Thank you {a}! Yours too, I like the way you describe your work.", "Appreciate it. Let's stay in touch."],
  ["Hey {b}, do you know anyone who could help with this?", "Let me think… I know someone. I'll introduce you.", "That would be amazing, thank you!", "No problem. Sending an intro now."],
  ["Long time no see {b}! How have you been?", "{a}!! It's been ages. All good, busy but happy. You?", "Same here. We should meet up when I'm in town.", "Definitely. Let me know the dates."],
  ["Hi {b}, saw your post about the trip. Any recommendations?", "Yes! I'll send you a list tonight.", "You're the best, thanks {b} 🙏"],
  ["Congrats on the new milestone {b}! 🎉", "Thank you so much {a}! Means a lot coming from you.", "You earned it. Celebrate properly!", "Planning on it 😄"],
];
